# Setup
title: Soy Gian Carlo Orcotoma
description: Vivo en Cusco - Per칰 y tengo 22 a침os. Soy desarrollador m칩vil y dise침ador gr치fico, me encanta crear cosas 游땔, te invito a conocerme m치s a continuaci칩n.
url: https://shafool.github.io/cv
avatar: /avatar.jpeg
paginate: 5
permalink: pretty
cover_image: /bg.jpeg
cover_bg_color: rgb(40, 73, 77)
cover_color: rgb(255, 255, 255)

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: shafool
  card: summary
logo: logo.png
social:
  name: Gian Orcotoma
  links:
    - https://github.com/shafool
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Gian Carlo Orcotoma Mormontoy
  url: https://github.com/shafool/
  email: giancarlozklm2015@gmail.com
